### ISSUE TITLE
如果是发送多张图片想做成QQ的效果怎么弄

### ISSUE THREAD

**Issue by jianjianhao** [chdo002/CDChatList#10]
这种我暂时还没想到好的方法，大佬能否指导下，是带网络请求的那种，只要是怎么保证多张图片发送顺序不乱

**Comment by chdo002** [comment]
用addMessagesToBottom
里面传的消息数组

**Comment by jianjianhao** [comment]
这个我看了，我是想实现类似QQ图片加载的效果，比方说网络慢的情况怎么处理

**Comment by chdo002** [comment]
那只能自定义一个cell了，可以在图片消息cell的基础上做定制

**Comment by jianjianhao** [comment]
嗯好的，有个bug是在iOS12.1模拟器是触发的，就是CTTextView在设置最大行数的时候不会调用set方法
<img width="601" alt="ede8ee22-bfcc-467c-b8dd-444163900dc6" src="https://user-images.githubusercontent.com/12797357/48596739-55949580-e995-11e8-9a2c-23f5888d601d.png">
不知道啥问题

**Comment by chdo002** [comment]
很奇怪的问题，我改个属性名就好了，可能和系统的属性冲突了之类的
现在更新了pod
