### ISSUE TITLE
与masonry宏定义的冲突

### ISSUE THREAD

**Issue by chjsun** [chdo002/CDChatList#5]
![image](https://user-images.githubusercontent.com/13481443/44571594-c459bc80-a7b3-11e8-9cd8-7dc9e51cee15.png)

这种类型的category对集成了masonry的项目极其不友好

**Comment by chjsun** [comment]
你的这个文件只有在CDChatListView中用来，并且只用了viewController属性，建议吧其他属性都注释掉，

**Comment by chdo002** [comment]
ok

**Comment by chdo002** [comment]
已经去掉了
